CREATE DATABASE IF NOT EXISTS linkforge CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE linkforge;

CREATE TABLE users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE short_links (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, code VARCHAR(64) NOT NULL UNIQUE, destination_url TEXT NOT NULL,
 is_active TINYINT(1) NOT NULL DEFAULT 1, expires_at DATETIME NULL, click_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
 last_clicked_at DATETIME NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_links_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX idx_links_user_created (user_id, created_at), INDEX idx_links_status_expiry (is_active, expires_at)
) ENGINE=InnoDB;
CREATE TABLE link_clicks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, short_link_id BIGINT UNSIGNED NOT NULL, clicked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 user_agent VARCHAR(512) NULL, ip_hash CHAR(64) NULL,
 CONSTRAINT fk_clicks_link FOREIGN KEY (short_link_id) REFERENCES short_links(id) ON DELETE CASCADE,
 INDEX idx_clicks_link_date (short_link_id, clicked_at)
) ENGINE=InnoDB;
CREATE TABLE login_attempts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(254) NOT NULL, attempted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_attempts_email_date (email, attempted_at)
) ENGINE=InnoDB;
